name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-service-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/build-push-action@v6
        with:
          context: ./service_a
          file:: ./service_a/Dockerfile
          push: true
          tags: ${{steps.ecr-login.outputs.registry}}/service_a:${{ github.sha }}

